Importing Dependencies

In [1]:
import pandas as pd

Loading Dataset

In [ ]:
df = pd.read_csv("D:\DA\Portfolio Projects\Procurement\Procurement KPI Analysis Dataset.csv")
#print first 5 rows of the dataset
print(df.head())

      PO_ID         Supplier  Order_Date Delivery_Date    Item_Category  \
0  PO-00001        Alpha_Inc  2023-10-17    2023-10-25  Office Supplies
1  PO-00002  Delta_Logistics  2022-04-25    2022-05-05  Office Supplies
2  PO-00003         Gamma_Co  2022-01-26    2022-02-15              MRO
3  PO-00004    Beta_Supplies  2022-10-09    2022-10-28        Packaging
4  PO-00005  Delta_Logistics  2022-09-08    2022-09-20    Raw Materials

  Order_Status  Quantity  Unit_Price  Negotiated_Price  Defective_Units  \
0    Cancelled      1176       20.13             17.81              NaN
1    Delivered      1509       39.32             37.34            235.0
2    Delivered       910       95.51             92.26             41.0
3    Delivered      1344       99.85             95.52            112.0
4    Delivered      1180       64.07             60.53            171.0

  Compliance
0        Yes
1        Yes
2        Yes
3        Yes
4         No

Data Cleaning

In [ ]:
#Changing into Datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'])
df['Delivery_Date'] = pd.to_datetime(df['Delivery_Date'])

In [9]:
#Check Nulls
df.isnull().sum()

PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

In [10]:
#Remove Duplicates
df.drop_duplicates(inplace=True)

In [11]:
#Overview of Data
print(df.shape)
print(df.describe())
print(df.isnull().sum())

(777, 11)
                          Order_Date                  Delivery_Date  \
count                            777                            690
mean   2022-12-28 23:15:31.274131456  2023-01-12 03:16:10.434782720
min              2022-01-01 00:00:00            2022-01-06 00:00:00
25%              2022-07-02 00:00:00            2022-07-19 18:00:00
50%              2022-12-24 00:00:00            2023-01-19 12:00:00
75%              2023-07-07 00:00:00            2023-07-18 00:00:00
max              2024-01-01 00:00:00            2024-01-12 00:00:00
std                              NaN                            NaN

          Quantity  Unit_Price  Negotiated_Price  Defective_Units
count   777.000000  777.000000        777.000000       641.000000
mean   1094.660232   58.283822         53.660721        74.803432
min      51.000000   10.840000          9.270000         0.000000
25%     615.000000   33.290000         30.460000        26.000000
50%    1075.000000   58.950000         53.800000        49.000000
75%    1548.000000   83.130000         76.550000       100.000000
max    5000.000000  109.170000        107.390000       321.000000
std     647.844551   28.101315         26.094930        69.187870
PO_ID                 0
Supplier              0
Order_Date            0
Delivery_Date        87
Item_Category         0
Order_Status          0
Quantity              0
Unit_Price            0
Negotiated_Price      0
Defective_Units     136
Compliance            0
dtype: int64

Feature Engineering

In [12]:
#Fix Missing Values
df['Defective_Units'] = df['Defective_Units'].fillna(0)

In [13]:
#Create a Delivery Flag
df['Delivery_Status'] = df['Delivery_Date'].apply(lambda x: "Delivered" if pd.notnull(x)else "Not Delivered")

In [14]:
#Create Negotiative Savings
df['Negotiative_Savings'] = df['Unit_Price'] - df['Negotiated_Price']

In [22]:
df.rename(columns={"Negotiative_Savings": "Negotiation_Savings"}, inplace=True)

In [16]:
#Create Total Spend
df["Total_Cost"] = df["Negotiated_Price"] * df["Quantity"]

In [17]:
#Defect Rate 
df['Defect_Rate'] = df['Defective_Units'] / df['Quantity']

In [18]:
#Delivery Time
df['Delivery_Time'] = (df['Delivery_Date']-df['Order_Date']).dt.days

In [19]:
#Compliance Status
df['Compliance_Status'] = df['Compliance'].map({"Yes":"Compliant","No":"Non-Compliant"})

Overview of New Dataset

In [23]:
df.head()

,PO_ID,Supplier,Order_Date,Delivery_Date,Item_Category,Order_Status,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Compliance,Delivery_Status,Negotiation_Savings,Total_Cost,Defect_Rate,Delivery_Time,Compliance_Status
0,PO-00001,Alpha_Inc,2023-10-17,2023-10-25,Office Supplies,Cancelled,1176,20.13,17.81,0.0,Yes,Delivered,2.32,20944.56,0.000000,8.0,Compliant
1,PO-00002,Delta_Logistics,2022-04-25,2022-05-05,Office Supplies,Delivered,1509,39.32,37.34,235.0,Yes,Delivered,1.98,56346.06,0.155732,10.0,Compliant
2,PO-00003,Gamma_Co,2022-01-26,2022-02-15,MRO,Delivered,910,95.51,92.26,41.0,Yes,Delivered,3.25,83956.60,0.045055,20.0,Compliant
3,PO-00004,Beta_Supplies,2022-10-09,2022-10-28,Packaging,Delivered,1344,99.85,95.52,112.0,Yes,Delivered,4.33,128378.88,0.083333,19.0,Compliant
4,PO-00005,Delta_Logistics,2022-09-08,2022-09-20,Raw Materials,Delivered,1180,64.07,60.53,171.0,No,Delivered,3.54,71425.40,0.144915,12.0,Non-Compliant

In [24]:
df.describe()

,Order_Date,Delivery_Date,Quantity,Unit_Price,Negotiated_Price,Defective_Units,Negotiation_Savings,Total_Cost,Defect_Rate,Delivery_Time
count,777,690,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,690.000000
mean,2022-12-28 23:15:31.274131456,2023-01-12 03:16:10.434782720,1094.660232,58.283822,53.660721,61.710425,4.623102,58396.005650,0.057800,10.776812
min,2022-01-01 00:00:00,2022-01-06 00:00:00,51.000000,10.840000,9.270000,0.000000,0.180000,772.800000,0.000000,-5.000000
25%,2022-07-02 00:00:00,2022-07-19 18:00:00,615.000000,33.290000,30.460000,11.000000,1.900000,22221.850000,0.020000,6.000000
50%,2022-12-24 00:00:00,2023-01-19 12:00:00,1075.000000,58.950000,53.800000,38.000000,3.650000,46776.360000,0.037508,11.000000
75%,2023-07-07 00:00:00,2023-07-18 00:00:00,1548.000000,83.130000,76.550000,85.000000,6.640000,83088.710000,0.098026,16.000000
max,2024-01-01 00:00:00,2024-01-12 00:00:00,5000.000000,109.170000,107.390000,321.000000,15.560000,432900.000000,0.357143,20.000000
std,NaN,NaN,647.844551,28.101315,26.094930,68.971194,3.455732,48236.432418,0.052700,5.729210

# EDA

Top Vendors by Spend

In [25]:
df.groupby("Supplier")['Total_Cost'].sum().sort_values(ascending=False)

Supplier
Beta_Supplies      9858665.90
Epsilon_Group      9851156.06
Delta_Logistics    9236240.47
Gamma_Co           8587921.71
Alpha_Inc          7839712.25
Name: Total_Cost, dtype: float64

Worst Vendors by Defect Rate

In [26]:
df.groupby("Supplier")['Defect_Rate'].mean().sort_values(ascending=False)

Supplier
Delta_Logistics    0.108666
Beta_Supplies      0.082723
Gamma_Co           0.044975
Epsilon_Group      0.026063
Alpha_Inc          0.018905
Name: Defect_Rate, dtype: float64

Best Negotiators

In [27]:
df.groupby("Supplier")['Negotiation_Savings'].mean().sort_values(ascending=False)

Supplier
Epsilon_Group      4.757229
Alpha_Inc          4.738369
Beta_Supplies      4.671538
Gamma_Co           4.642168
Delta_Logistics    4.337719
Name: Negotiation_Savings, dtype: float64

Compliance Check

In [28]:
df.groupby("Supplier")['Compliance_Status'].value_counts()

Supplier         Compliance_Status
Alpha_Inc        Compliant            132
                 Non-Compliant          9
Beta_Supplies    Compliant            118
                 Non-Compliant         38
Delta_Logistics  Compliant            104
                 Non-Compliant         67
Epsilon_Group    Compliant            163
                 Non-Compliant          3
Gamma_Co         Compliant            123
                 Non-Compliant         20
Name: count, dtype: int64

Delta Logistics has most Non-Compliance Status

Cost vs Quality

In [29]:
df.groupby("Supplier").agg({
            "Total_Cost":"sum",
            "Defect_Rate":"mean"
}).sort_values(by="Total_Cost",ascending=False)

                 Total_Cost  Defect_Rate
Supplier
Beta_Supplies    9858665.90     0.082723
Epsilon_Group    9851156.06     0.026063
Delta_Logistics  9236240.47     0.108666
Gamma_Co         8587921.71     0.044975
Alpha_Inc        7839712.25     0.018905

Delta_Logistics has high spend but also high defects

In [30]:
df.to_csv("Procurement.csv",index=False)